"""empty message

Revision ID: 027b53a9a2f8
Revises: 5126c07eefb4
Create Date: 2020-04-04 19:01:32.641217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027b53a9a2f8'
down_revision = '5126c07eefb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('description', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'description')
    # ### end Alembic commands ###
