"""empty message

Revision ID: 0398f386269b
Revises: 5100ac823b27
Create Date: 2020-04-04 17:36:16.498714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0398f386269b'
down_revision = '5100ac823b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('is_deletable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'is_deletable')
    # ### end Alembic commands ###
