"""empty message

Revision ID: 3a0990ffb7ea
Revises: 5a9bb3565704
Create Date: 2020-04-05 11:34:56.425319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0990ffb7ea'
down_revision = '5a9bb3565704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('description', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'description')
    # ### end Alembic commands ###
