"""empty message

Revision ID: 5126c07eefb4
Revises: ba83abe0b9fd
Create Date: 2020-04-04 18:34:31.474333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5126c07eefb4'
down_revision = 'ba83abe0b9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelled_matches',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'offer_id')
    )
    op.drop_table('matches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name='matches_offer_id_fkey'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='matches_request_id_fkey'),
    sa.PrimaryKeyConstraint('request_id', 'offer_id', name='matches_pkey')
    )
    op.drop_table('cancelled_matches')
    # ### end Alembic commands ###
