"""empty message

Revision ID: 5a9bb3565704
Revises: ce442f752e9b
Create Date: 2020-04-05 10:31:38.913358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9bb3565704'
down_revision = 'ce442f752e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('offers', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'start_date')
    op.drop_column('requests', 'end_date')
    op.drop_column('offers', 'start_date')
    op.drop_column('offers', 'end_date')
    # ### end Alembic commands ###
