"""empty message

Revision ID: 8feee5d4383f
Revises: 46026b11ef14
Create Date: 2020-04-04 19:43:44.336952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8feee5d4383f'
down_revision = '46026b11ef14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'timestamp')
    # ### end Alembic commands ###
