"""empty message

Revision ID: a84e718282c1
Revises: 8feee5d4383f
Create Date: 2020-04-04 20:21:18.554378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84e718282c1'
down_revision = '8feee5d4383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'offers_history', 'users', ['user_id'], ['id'])
    op.add_column('requests_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'requests_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests_history', type_='foreignkey')
    op.drop_column('requests_history', 'user_id')
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'user_id')
    # ### end Alembic commands ###
