"""empty message

Revision ID: ce442f752e9b
Revises: a84e718282c1
Create Date: 2020-04-05 00:24:58.958128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce442f752e9b'
down_revision = 'a84e718282c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('area', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('number_of_rooms', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('description', sa.String(length=800), nullable=True))
    op.add_column('requests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'longitude')
    op.drop_column('requests', 'latitude')
    op.drop_column('requests', 'description')
    op.drop_column('offers', 'number_of_rooms')
    op.drop_column('offers', 'longitude')
    op.drop_column('offers', 'latitude')
    op.drop_column('offers', 'area')
    # ### end Alembic commands ###
